name = "identity-dynamic"
account_id = "804ece9da084d891d089f87d84b0f6ad"
workers_dev = false
compatibility_date = "2024-11-25"
main = "src/main.js"


routes = [
	{ pattern = "", custom_domain = true }	
]

# wrangler kv:namespace create IDENTITY_DYNAMIC_THEME_STORE

[[kv_namespaces]] 
binding = "IDENTITY_DYNAMIC_THEME_STORE"
id = "7318bd0150414f7fbfe1ace65a47bf4d" # unique ID of the previously created namespace

[vars]
BEARER_TOKEN = cf_identity_test_page
CORS_ORIGIN = "https://bournemd.com/debug" # This should be the route pattern domain /debug (https://example.com/debug)
ACCOUNT_ID = "804ece9da084d891d089f87d84b0f6ad"
ORGANIZATION_ID = "804ece9da084d891d089f87d84b0f6ad"
ORGANIZATION_NAME = "teammd"
DEBUG = "true"
TARGET_GROUP = "" # Define the "special group" that you want to use for notification

[site]
bucket = "./build" 

[build]
command = "npm run build"